/////////////////////////////////////////////////////////////////////////////
// Name:        cspellcheck.h
// Purpose:
// Author:      Gerald Brandt
// Modified by:
// Created:     Wed 10 Oct 2012 13:07:20 CDT
// RCS-ID:
// Copyright:   (c) Majentis Technologies
// Licence:
/////////////////////////////////////////////////////////////////////////////

/*
// Generated by DialogBlocks (unregistered), Wed 10 Oct 2012 13:07:20 CDT

#ifndef _CSPELLCHECK_H_
#define _CSPELLCHECK_H_




////@begin includes
#include "wx/listctrl.h"
////@end includes



////@begin forward declarations
class wxListCtrl;
////@end forward declarations


////@begin control identifiers
#define ID_CSPELLCHECK 10012
#define ID_TEXTCTRL 10021
#define ID_LISTCTRL 10010
#define ID_SPELL_IGNORE 10001
#define ID_SPELL_ADD 10002
#define ID_SPELL_ENTER 10003
#define ID_SPELL_MORE 10004
#define ID_SPELL_GLOBAL 10000
#define SYMBOL_CSPELLCHECK_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxWANTS_CHARS|wxTAB_TRAVERSAL
#define SYMBOL_CSPELLCHECK_TITLE _("Spell Check")
#define SYMBOL_CSPELLCHECK_IDNAME ID_CSPELLCHECK
#define SYMBOL_CSPELLCHECK_SIZE wxSize(400, 300)
#define SYMBOL_CSPELLCHECK_POSITION wxDefaultPosition
////@end control identifiers

#define ID_SPELL_SELECT1 20000
#define ID_SPELL_SELECT2 20001
#define ID_SPELL_SELECT3 20002
#define ID_SPELL_SELECT4 20003
#define ID_SPELL_SELECT5 20004



class cSpellCheck: public wxDialog
{
    DECLARE_DYNAMIC_CLASS( cSpellCheck )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    cSpellCheck();
    cSpellCheck( wxWindow* parent, wxWindowID id = SYMBOL_CSPELLCHECK_IDNAME, const QString& caption = SYMBOL_CSPELLCHECK_TITLE, const wxPoint& pos = SYMBOL_CSPELLCHECK_POSITION, const wxSize& size = SYMBOL_CSPELLCHECK_SIZE, long style = SYMBOL_CSPELLCHECK_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CSPELLCHECK_IDNAME, const QString& caption = SYMBOL_CSPELLCHECK_TITLE, const wxPoint& pos = SYMBOL_CSPELLCHECK_POSITION, const wxSize& size = SYMBOL_CSPELLCHECK_SIZE, long style = SYMBOL_CSPELLCHECK_STYLE );

    /// Destructor
    ~cSpellCheck();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin cSpellCheck event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_SPELL_IGNORE
    void OnSpellIgnoreClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_SPELL_ADD
    void OnSpellAddClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_SPELL_ENTER
    void OnSpellEnterClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_SPELL_MORE
    void OnSpellMoreClick( wxCommandEvent& event );

////@end cSpellCheck event handler declarations

    void OnSpellSelect1( wxCommandEvent &event) ;
    void OnSpellSelect2( wxCommandEvent &event) ;
    void OnSpellSelect3( wxCommandEvent &event) ;
    void OnSpellSelect4( wxCommandEvent &event) ;
    void OnSpellSelect5( wxCommandEvent &event) ;

////@begin cSpellCheck member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const QString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const QString& name );
////@end cSpellCheck member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin cSpellCheck member variables
    wxTextCtrl* mBadWord;
    wxListCtrl* mSpellList;
    wxCheckBox* mGlobal;
////@end cSpellCheck member variables
};

#endif
    // _CSPELLCHECK_H_

    */
